### ISSUE TITLE
PHP Inspections (EA Ultimate) Website Redesign

### ISSUE THREAD

**Issue by azdanov** [kalessil/kalessil.github.io#1]
Hello, @kalessil!

I'm a fan of your plugin, _PHP Inspections (EA Extended)_, and wanted to say thanks for making it.

That's why I wanted to try and update the looks of the _EA Ultimate_ page. _(It's also a good practice for me.)_

Here's a first version: https://awesome-jepsen-eff5a1.netlify.com/
And GitHub: https://github.com/azdanov/ea-ultimate

Tell me what do you think, and if it will be useful.

![awesome-jepsen-eff5a1 netlify com_](https://user-images.githubusercontent.com/6123841/56313251-dd581900-615a-11e9-9869-0ad94860ce94.png)

**Comment by kalessil** [comment]
Hi @azdanov, looks really great and I find it VERY useful. I'll check over holidays (currently it's Easter in Germany, so Monday is also a holiday) and will be back with feedback.

**Comment by azdanov** [comment]
I've added dynamic docs generation. This should add some value to the website/app, apart from selling.

I was thinking of linking an Algolia search, similar to [Tailwind CSS](https://tailwindcss.com/). Probably an overkill at this point.

A better copy text is currently needed for both index and ea-ultimate pages. To showcase all the features, basically marketing to persuade people to use and potentially buy this plugin.

The order of Docs is the same as in GitHub (alphabetical), which doesn't make much sense in a website context.

I was also thinking about payment options for EA Ultimate. What about Stripe or some similar external service? Not that the current approach is bad, but it may dissuade some customers.

P.S: Had lots of fun building this. I was looking a reason to recreate [ReactJS Docs](https://reactjs.org/) website.

**Comment by kalessil** [comment]
Awesome!

Algolia is currently overkill, btw will the new version be indexed by search engines well?
Copy text, I'll update, but we can pick it one-to-one currently.

Stripe: not yet, I need still create a licenses management solution (top 1 in my list).

> Had lots of fun building this. I was looking a reason to recreate ReactJS Docs website.
Yeah, look great =)

PS: feedback
- Can /ea-ultimate be made a homepage as well?
- Can the icons be centered?
- The design is mobile friendly, thank you!
- I planned to relocate docs into the plugin directly but would like to hear your thoughts on this, as linked in the design.
- How complex it'll be to add blog pages, as in current solution?

**Comment by azdanov** [comment]
> will the new version be indexed by search engines well?

Yeah. 
> Just send us the URL of your documentation, and we’ll run the crawler every 24h so you’re always up-to-date.

> Can /ea-ultimate be made a homepage as well

What do you mean by homepage? When I visit `/` it should land on ea-ultimate? Or separate ea-extended from ea-ultimate in two different domains/projects?

> Can the icons be centered?

Sure!

> into the plugin directly

Why not both? Of course, it depends on the source. If files are kept in public repo as `.md` files then it's easy to embed in the website.

The website has the benefit of being searchable in Google, so you will get more traffic for properly structured documentation pages. People might search `PHP Security` and end up finding this plugin, or even just some explanation on how to manually fix things. Which is IMO good.

Also `Algolia is currently overkill` is true at this point, but it doesn't add much overhead, and it makes the website look professional.

> How complex it'll be to add blog pages, as in current solution?

Not difficult. There are multiple approaches. One is to use something like [Contentful](https://www.contentful.com/) which will serve as a database and authentication. It's also possible with [Netlify CMS](https://www.netlifycms.org/) requires a bit more work, but is free. Or it's possible to manually write markdown files inside the repo, e.g [src/content/blog](https://github.com/azdanov/azdanov.github.io/tree/master/src/content/blog) and push to GitHub.

If there are any other remarks I'm happy to make more improvements.

**Comment by azdanov** [comment]
I've added Netlify CMS, seems robust enough. It uses Netlify Identity for login, and Netlify Gateway to send new blog post straight into GitHub repo when published. A bit of vendor lock here, but it's free. The only requirement is to be hosted on Netlify and enable the functionality. Of course, it's possible to use another place for hosting, and authentication.

What fields should a blog include? I've included some basic ones: Title, Publish Date, Description, Image (optional), Body and Tags.

Now need to do a blog feed with pagination. Maybe filtering by tags. And an individual post page.

Here are some screenshots:

![1](https://user-images.githubusercontent.com/6123841/56691467-b5336180-66e8-11e9-827f-26d0819d15c4.PNG)
![2](https://user-images.githubusercontent.com/6123841/56691470-b6fd2500-66e8-11e9-9d95-83070c78ea8d.PNG)
![3](https://user-images.githubusercontent.com/6123841/56691474-b8c6e880-66e8-11e9-998b-a68799eca62f.PNG)
![4](https://user-images.githubusercontent.com/6123841/56691481-bb294280-66e8-11e9-9ecf-5060ace0a53e.PNG)

**Comment by azdanov** [comment]
I've added a blog feed, with some demo posts. And individual tags with filtering.

Now what remains is an individual blog page.

**Comment by azdanov** [comment]
A blog page is done, more or less. Also, I've tried making the CMS editing page resemble the blog template by using the same font and styles.

Added a plugin to generate a `sitemap.xml`. This should be useful by submitting to Google, Bing, etc. You can check it out here: https://awesome-jepsen-eff5a1.netlify.com/sitemap.xml

**Comment by azdanov** [comment]
What do you think so far @kalessil?

There are still some design issues to iron out, but most relevant functionality is there.

If you want to try out the CMS functionality for the blog I can send an invitation to your email (this is how netlify identity works.)

**Comment by kalessil** [comment]
Checking it out @azdanov, also trying to get thru my emails...

**Comment by azdanov** [comment]
Ah, thanks for you time, I was afraid GitHub notifications were broken. Happened to me once.
